LPS-147943 | master
hongvo2308/liferay-portal pull request #20
Opened 2022-04-01 08:35 UTC by sontruongces

@hongvo2308 Please help me review this PR and give me feedback. Thank you!
Ticket: [LPS-147943](https://issues.liferay.com/browse/LPS-147943)

2022-04-01 10:33 UTC, hongvo2308 requested changes

2022-04-01 10:33 UTC, hongvo2308 commented on modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/management_toolbar/ResultsBar.js
> +								(itemsTotal === 1) ? Liferay.Language.get('x-result-for-x') : Liferay.Language.get('x-results-for-x'),
@sontruongces 
Can we try to use Liferay.Language.get((itemsTotal === 1) ?'x-result-for-x':'x-results-for-x')

2022-04-04 03:43 UTC, sontruongces commented
@hongvo2308 I have just rebased and updated the fix. Please help me to review it again. Thank you so much!

2022-04-04 03:44 UTC, hongvo2308 commented
@sontruongces Please rebase the upstream/master and resolve the confilct
Thanks.

2022-04-04 04:39 UTC, hongvo2308 commented
Forwarded https://github.com/liferay-ts-reviewer/liferay-portal/pull/36
Thank you.

2022-04-04 04:39 UTC, closed without merging