LPS-149558,LPS-149559
hongvo2308/liferay-portal pull request #29
Opened 2022-05-17 08:03 UTC by tototrinh

@hongvo2308 Please help me review this PR and leave your comments. This change is based on [brianchandotcom's comment](https://github.com/brianchandotcom/liferay-portal/pull/117348#issuecomment-1126563733). Thanks.

2022-05-17 09:28 UTC, hongvo2308 requested changes

2022-05-17 09:28 UTC, hongvo2308 commented on modules/apps/portal-language/portal-language-override-test/src/testIntegration/java/com/liferay/portal/language/override/service/test/PLOEntryLocalServiceTest.java
> +				RandomTestUtil.randomString());
@tototrinh 
Can you try to add the `Assert.fail();` at the end of the try block for the cases that throw the exception.

2022-05-17 11:19 UTC, tototrinh commented
Thanks for your feedback. I updated the code, please help take a look again.

2022-05-18 02:12 UTC, hongvo2308 commented
Forwarded https://github.com/liferay-ts-reviewer/liferay-portal/pull/57
Thank you.

2022-05-18 02:12 UTC, closed without merging