LPP-42880 Categories Associated Asset Types are not being saved or modified correctly
hongvo2308/liferay-portal pull request #9
Opened 2021-10-19 09:16 UTC by thuycao-gs

2021-10-21 02:52 UTC, hongvo2308 requested changes

2021-10-21 02:52 UTC, ces-hongvo commented on modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/edit_vocabulary_settings.jspf
> +		if (index < (selectedClassNameIds.length - 1)) {
@thuycao-gs please export this length to be a variable.

2021-10-25 04:11 UTC, ces-hongvo commented on modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/edit_vocabulary_settings.jspf
> +		indexes.Append(String.valueOf(index));
@thuycao-gs Please correct Append to append

2021-10-25 04:36 UTC, thuycao-gs commented on modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/edit_vocabulary_settings.jspf
> +		indexes.Append(String.valueOf(index));
@hongvo2308 I updated. Thank you

2022-04-01 07:36 UTC, closed without merging